name: Deploy to Preview Channel

on:
  push:
    branches:
      - develop
  # pull_request:
  #   branches:
  #     - develop
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    env:
      APP_MODE: dev
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      - run: npm install && CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}"
          expires: 30d
          projectId: dev-convert-web2mobile-app
          channelId: live